###########
# site.title

title:    'The Great Story of Wallace'
subtitle: 'Minecraft Prison Breaker'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
